services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - 3309:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

